syntax = "All"
column_width = 120
line_endings = "Unix"
indent_type = "Spaces"
indent_width = 4
quote_style = "ForceSingle"
call_parentheses = "None"
collapse_simple_statement = "Never"
space_after_function_names = "Always"
block_newline_gaps = "Preserve"

[sort_requires]
enabled = false
